### ISSUE TITLE
Update required due to deprecation of Document List

### ISSUE THREAD

**Issue by pbavinck** [google/gdata-python-client#3]
Code depending on https://docs.google.com/feeds/, https://docs.googleusercontent.com/ and
https://spreadsheets.google.com/feeds/ need to be updated according to https://developers.google.com/drive/web/migration.

**Comment by aliafshar** [comment]
That code should be removed since the new API depends on a different client library. Documents List API should be going away soon.

**Comment by haight6716** [comment]
I'm curious what the resolution to this is?  I got a scary email from google saying it seems like I'm using one of these APIs.  I'm appending rows to a google sheet using gdata.  I'm not listing files.  Am I going to be affected?  I wish google provided a sure way to know what API requests I'm making and whether they are being deprecated.
