### ISSUE TITLE
Support for v3 of Google Calendar API?

### ISSUE THREAD

**Issue by hany** [google/gdata-python-client#7]
Hi There,

It seems that Google has deprecated v2 of the Calendar API. Any plans on implementing v3?

https://code.google.com/p/googlecl/issues/detail?id=567

**Comment by aliafshar** [comment]
Yes, that is supported in this library: https://github.com/google/google-api-python-client

**Comment by hany** [comment]
Thanks for responding so fast. I do like the implementation of gdata. Is gdata being deprecated as a whole?

**Comment by hany** [comment]
Just to clarify my last point. gdata hides the implementation of OAuth, which is very nice. the google-api-python-client requires you to implement OAuth yourself. Do you know of any libraries that would hide this implementation?

**Comment by aliafshar** [comment]
Well I can't really comment on that, but newer APIs are not using GData.

google-api-python-client should hide auth pretty similarly to GData lib. You shouldn't have to implement it yourself at all.

**Comment by hany** [comment]
Thanks, however google-api-python-client doesn't hide much of OAuth. It requires you to jump through all the hoops of OAuth such as storing and requesting refresh and access tokens. This is the implementation I was hoping would be hidden.

Thanks for your time. I will look elsewhere.
